"""
TechDeck Fidget Spinner

A standalone, frameless, always-on-top fidget spinner drawn as HAND-EDITABLE
PIXEL ART, like the moth (`MOTH_FRAMES`): edit the `SPINNER_ART` grid below.

It's a four-arm spinner kept PERFECTLY 4-fold symmetric by construction: you only
draw ONE arm — the TOP arm plus the top half of the hub — and `_enforce_4fold`
rotates it 90/180/270 into the other three arms at load. So edit the top of the
grid; whatever you put in the other three arms is ignored (overwritten by the
rotated top arm). The grid is rendered to a pixmap once; spinning rotates that
pixmap with smoothing OFF, so the pixels stay hard-edged at every angle.

Editing the art — each cell is one character:
    .  transparent (a dark OUTLINE is auto-traced around every filled cell,
       and around the bearing holes, just like the moth's silhouette outline)
    B  body  -> theme accent_pressed   (the hub + the arms)
    W  wing  -> theme accent_two        (the lobes / "wings")
    R  ring  -> theme text              (the bright bearing rings)
    H  highlight -> a lighter wing tone (optional shading; place by hand)
    o  outline tone                     (optional hand-drawn dark detail)

Keep the grid SQUARE and ODD-sized (so it has a true centre cell), keep the hub
centred, and keep art within the inscribed circle (radius = half the grid) or it
clips as it spins. Keep every row the same length.

  - Click anywhere on it to add spin (and drag to move it).
  - It does NOT close on double-click (that fought with clicking to spin);
    `/clear` puts it away (see CommandHandler.stop_session_effects).

Tip: preview edits without launching the whole app with
`python tools/preview_spinner.py`.
"""

import math

from PySide6.QtWidgets import QWidget
from PySide6.QtCore import Qt, QTimer, QPointF
from PySide6.QtGui import QPainter, QColor, QPixmap


# ── Hand-editable pixel art — DRAW THE TOP ARM ONLY (legend in docstring) ────
# The other three arms are generated by rotating the top arm (see _enforce_4fold).
SPINNER_ART = [
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "...............o..............................o...............",
    "............ooooooHH......................HHHHoHHH............",
    "..........ooooooooooHH..................HHooooooooHH..........",
    ".........HooooooooooooHH..............HHooooooooooooo.........",
    ".........HoooRRRRRRoooooo............oooWooRRRRRRoooo.........",
    "........HoooRRRooRRRooWWoo..........ooWWWoRRRooRRRoooo........",
    "........HooRRoooooRRRoWWWoo........ooWWWoRRRoooooRRooo........",
    "........HooRRo....oRRooWWWoo......oooWWWoRRo....oRRooo........",
    ".......ooooRoo....oRRoooWWWoo....ooooWWWoRRo....ooRoooo.......",
    "........HooRoo....oRRooooWWWoo..oooooWWWoRRo....ooRooo........",
    "........HooRRo...ooRRooooWWWWoHHoooooWWWoRRoo...oRRooo........",
    "........HooRRRooooRRooHoooWWWWooWWWoWWWWooRRooooRRRooH........",
    "........HoooRRRRRRRRoHHHoWWWBBBBBBWWWWWWWoRRRRRRRRoooH........",
    ".........HoooRRRRRooWWHWWBBBBBBBBBBBBWWWWWooRRRRRoooH.........",
    ".........HoWWooooooWWWWWBBBBooooooBBBBWWWWHoooooooooH.........",
    "..........HoWWWWWWWWWWWBBBoooRRRRoooBBBWWHHHooooWWoH..........",
    "..........HoWWWWWWWWWWBBooRRRRRRRRRRooBBWWHooooWWWoH..........",
    "...........ooWWWWWWWWBBooRRRRRRRRRRRRooBBWooooWWWoo...........",
    "............ooooooWWBBBoRRRRRRRRRRRRRRoBBBWoWWWWoo............",
    ".............ooooooWBBoRRRRRRR..RRRRRRRoBBWWWWWoo.............",
    "..............ooooWWBBoRRRRR......RRRRRoBBWWWWoo..............",
    "...............oooWBBooRRRR........RRRRooBBWWoo...............",
    "................ooWBBoRRRRR........RRRRRoBBWoo................",
    ".................HoBBoRRRR..........RRRRoBBoH.................",
    ".................HoBBoRRRR..........RRRRoBBoH.................",
    "................ooWBBoRRRRR........RRRRRoBBWoo................",
    "...............ooWWBBooRRRR........RRRRooBBWooo...............",
    "..............ooWWWWBBoRRRRR......RRRRRoBBWWoooo..............",
    ".............ooWWWWWBBoRRRRRRR..RRRRRRRoBBWoooooo.............",
    "............ooWWWWoWBBBoRRRRRRRRRRRRRRoBBBWWoooooo............",
    "...........ooWWWooooWBBooRRRRRRRRRRRRooBBWWWWWWWWoo...........",
    "..........HoWWWooooHWWBBooRRRRRRRRRRooBBWWWWWWWWWWoH..........",
    "..........HoWWooooHHHWWBBBoooRRRRoooBBBWWWWWWWWWWWoH..........",
    ".........HoooooooooHWWWWBBBBooooooBBBBWWWWWooooooWWoH.........",
    ".........HoooRRRRRooWWWWWBBBBBBBBBBBBWWHWWooRRRRRoooH.........",
    "........HoooRRRRRRRRoWWWWWWWBBBBBBWWWoHHHoRRRRRRRRoooH........",
    "........HooRRRooooRRooWWWWoWWWooWWWWoooHooRRooooRRRooH........",
    "........oooRRo...ooRRoWWWoooooHHoWWWWooooRRoo...oRRooH........",
    "........oooRoo....oRRoWWWooooo..ooWWWooooRRo....ooRooH........",
    ".......ooooRoo....oRRoWWWoooo....ooWWWoooRRo....ooRoooo.......",
    "........oooRRo....oRRoWWWooo......ooWWWooRRo....oRRooH........",
    "........oooRRoooooRRRoWWWoo........ooWWWoRRRoooooRRooH........",
    "........ooooRRRooRRRoWWWoo..........ooWWooRRRooRRRoooH........",
    ".........ooooRRRRRRooWooo............ooooooRRRRRRoooH.........",
    ".........oooooooooooooHH..............HHooooooooooooH.........",
    "..........HHooooooooHH..................HHoooooooooo..........",
    "............HHHoHHHH......................HHoooooo............",
    "...............o..............................o...............",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
    "..............................................................",
]

# 4-fold symmetry now lives in techdeck.ui.pixel_art (shared with .tdart
# spinner variants); see enforce_4fold there.
from techdeck.ui.pixel_art import enforce_4fold as _enforce_4fold

# The symmetric grid actually rendered (top arm rotated into all four).
_ART = _enforce_4fold(SPINNER_ART)
CELL = 5                                 # px per art cell
_ART_H = len(_ART)
_ART_W = max(len(r) for r in _ART)


def _render_spinner_pixmap(colors: dict) -> QPixmap:
    """Render the symmetric art to a pixmap: auto-trace a dark outline around it
    (and the holes), then paint each cell in its themed colour."""
    cmap = {"B": colors["body"], "W": colors["wing"], "R": colors["ring"],
            "H": colors["highlight"], "o": colors["outline"]}
    rows = _ART

    def filled(x, y):
        return 0 <= y < _ART_H and 0 <= x < len(rows[y]) and rows[y][x] != "."

    pm = QPixmap(_ART_W * CELL, _ART_H * CELL)
    pm.fill(Qt.GlobalColor.transparent)
    p = QPainter(pm)
    p.setPen(Qt.PenStyle.NoPen)
    # Outline pass: every empty cell touching a filled cell (silhouette + holes).
    for y in range(_ART_H):
        for x in range(_ART_W):
            if filled(x, y):
                continue
            if any(filled(x + dx, y + dy)
                   for dx in (-1, 0, 1) for dy in (-1, 0, 1) if dx or dy):
                p.fillRect(x * CELL, y * CELL, CELL, CELL, colors["outline"])
    # Body pass: each art cell in its colour.
    for y in range(_ART_H):
        row = rows[y]
        for x in range(len(row)):
            ch = row[x]
            if ch == ".":
                continue
            p.fillRect(x * CELL, y * CELL, CELL, CELL, cmap.get(ch, colors["body"]))
    p.end()
    return pm


def _render_variant_pixmap(variant: str):
    """Render an equipped store spinner with its OWN fixed palette (not the
    theme). Returns None if it can't be loaded so the caller falls back to the
    default spinner.

    `beyblade:` variants are composed at render time from three separate part
    sprites (top / bottom / centre) so the player can mix parts across designs;
    the composite is never stored.

    Symmetry is per-sprite. The 4-fold enforcer stamps the top arm into all four
    quadrants, which is right for the built-in spinner but SHREDS a 180 degree
    design — so it only runs when the sprite asks for it.
    """
    import sys
    from pathlib import Path
    from techdeck.ui import pixel_art
    from techdeck.ui import beyblade
    choice = beyblade.parse_variant(variant)
    if choice is not None:
        data = beyblade.compose(choice)
        return None if data is None else pixel_art.render(data, scale=CELL)
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        base = Path(sys._MEIPASS) / "assets" / "sprites"
    else:
        base = Path(__file__).resolve().parents[3] / "assets" / "sprites"
    fn = base / f"{variant}.tdart"
    if not fn.exists():
        return None
    try:
        data = pixel_art.load(fn)
        if int(data.get("symmetry", 4)) == 4:
            data = pixel_art.enforce_4fold_data(data)
        return pixel_art.render(data, scale=CELL)
    except Exception:
        return None


class FidgetSpinnerWindow(QWidget):
    """Frameless, always-on-top pixel-art four-arm spinner. Click to add spin,
    drag to move. Closed via /clear (no double-click-to-close)."""

    # Sized per instance from the ART's own reach, not the grid — see
    # _content_radius. Kept as a class attr for anything that reads it.
    WINDOW_SIZE = max(_ART_H, _ART_W) * CELL

    FRAME = 0.016         # seconds per tick (~60fps)
    FRICTION = 0.9985     # per ~60fps frame — low, so a flick keeps it spinning
    CLICK_IMPULSE = 3.0   # radians/sec added per click
    # The art is 4-fold symmetric, so it looks identical every 90 deg. Once the
    # per-frame rotation reaches ~45 deg the eye reads each step as going
    # BACKWARD (wagon-wheel strobe), and at 90 deg/frame it looks frozen — that's
    # the "locks up and slows down" on rapid clicks. Cap the velocity so a frame
    # never rotates far enough to alias; the spin stays fast but always forward.
    MAX_VELOCITY = math.radians(44) / FRAME   # ~7.6 rev/s, just under the 45/frame strobe

    def __init__(self, parent=None, variant=None):
        super().__init__(parent)
        self._angle = 0.0      # radians
        self._velocity = 1.0   # radians/sec
        # An equipped store variant (e.g. "spinner_beyblade") renders from its
        # own .tdart with its own fixed palette; otherwise the default themed
        # spinner is used.
        self._pixmap = _render_variant_pixmap(variant) if variant else None
        if self._pixmap is None:
            self._pixmap = _render_spinner_pixmap(self._theme_colors())

        self.setWindowFlags(
            Qt.WindowType.FramelessWindowHint
            | Qt.WindowType.WindowStaysOnTopHint
            | Qt.WindowType.Tool
        )
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        # The window must fit the art's SWEEP, not its bounding box. Several
        # designs paint out past the inscribed circle (silver_fang reaches r=34
        # on a 62-cell grid whose inscribed radius is 30.5), so those corners
        # swung outside a bounding-box-sized window and got clipped as it spun.
        # Measure how far the art actually reaches and size to twice that.
        size = self._content_diameter()
        self.WINDOW_SIZE = size
        self.setFixedSize(size, size)
        self.setCursor(Qt.CursorShape.PointingHandCursor)

        self._timer = QTimer(self)
        self._timer.setInterval(16)  # ~60fps
        self._timer.timeout.connect(self._tick)
        self._timer.start()

        self._drag_pos = None

    @staticmethod
    def _theme_colors() -> dict:
        """The original theme-palette colour set: body (hub/arms) = pressed accent,
        wings = secondary accent_two (the CTA slot — where cyberpunk's red/pink
        lives), bearing rings = text, outline = a darkened accent, and an optional
        highlight = a lighter wing tone."""
        try:
            from techdeck.ui.theme_manager import get_theme_manager
            pal = get_theme_manager().get_current_palette()
            body, wing = QColor(pal.accent_pressed), QColor(pal.accent_two)
            ring, outline = QColor(pal.text), QColor(pal.accent).darker(300)
        except Exception:
            body, wing = QColor(0x1F, 0x67, 0x90), QColor(0xF5, 0xC5, 0x18)
            ring, outline = QColor(0xEC, 0xEC, 0xEC), QColor(0x10, 0x28, 0x38)
        return {
            "body": body,
            "wing": wing,
            "ring": ring,
            "outline": outline,
            "highlight": wing.lighter(150),
        }

    def _tick(self):
        self._velocity *= self.FRICTION
        self._angle += self._velocity * self.FRAME
        self.update()

    def mousePressEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            # Clamp so it never spins fast enough to strobe/alias backward.
            self._velocity = min(self._velocity + self.CLICK_IMPULSE,
                                 self.MAX_VELOCITY)
            self._drag_pos = event.globalPosition().toPoint()

    def mouseMoveEvent(self, event):
        if self._drag_pos is not None and event.buttons() & Qt.MouseButton.LeftButton:
            delta = event.globalPosition().toPoint() - self._drag_pos
            self.move(self.pos() + delta)
            self._drag_pos = event.globalPosition().toPoint()

    def mouseReleaseEvent(self, event):
        self._drag_pos = None

    def _content_diameter(self) -> int:
        """Twice the furthest opaque pixel from the centre, plus a pixel of
        slack — the smallest square that can never clip the art at any angle."""
        img = self._pixmap.toImage()
        w, h = img.width(), img.height()
        cx, cy = (w - 1) / 2.0, (h - 1) / 2.0
        best = 0.0
        for y in range(h):
            for x in range(w):
                if img.pixelColor(x, y).alpha() > 0:
                    d = (x - cx) ** 2 + (y - cy) ** 2
                    if d > best:
                        best = d
        return int(math.ceil(math.sqrt(best) * 2)) + 2

    def paintEvent(self, event):
        painter = QPainter(self)
        # Smoothing OFF keeps the pixels hard-edged at every rotation angle.
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, False)
        painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, False)
        painter.translate(self.WINDOW_SIZE / 2.0, self.WINDOW_SIZE / 2.0)
        painter.rotate(math.degrees(self._angle))
        # Float offset so the art centre sits exactly on the rotation pivot (an
        # int offset on an odd-sized pixmap left it a half-pixel off -> wobble).
        painter.drawPixmap(QPointF(-self._pixmap.width() / 2.0,
                                   -self._pixmap.height() / 2.0), self._pixmap)
        painter.end()
