"""
TechDeck Fidget Spinner

A standalone, frameless, always-on-top fidget spinner drawn as HAND-EDITABLE
PIXEL ART, like the moth (`MOTH_FRAMES`): edit the `SPINNER_ART` grid below.

It's a four-arm spinner kept PERFECTLY 4-fold symmetric by construction: you only
draw ONE arm — the TOP arm plus the top half of the hub — and `_enforce_4fold`
rotates it 90/180/270 into the other three arms at load. So edit the top of the
grid; whatever you put in the other three arms is ignored (overwritten by the
rotated top arm). The grid is rendered to a pixmap once; spinning rotates that
pixmap with smoothing OFF, so the pixels stay hard-edged at every angle.

Editing the art — each cell is one character:
    .  transparent (a dark OUTLINE is auto-traced around every filled cell,
       and around the bearing holes, just like the moth's silhouette outline)
    B  body  -> theme accent_pressed   (the hub + the arms)
    W  wing  -> theme accent_two        (the lobes / "wings")
    R  ring  -> theme text              (the bright bearing rings)
    H  highlight -> a lighter wing tone (optional shading; place by hand)
    o  outline tone                     (optional hand-drawn dark detail)

Keep the grid SQUARE and ODD-sized (so it has a true centre cell), keep the hub
centred, and keep art within the inscribed circle (radius = half the grid) or it
clips as it spins. Keep every row the same length.

  - Click anywhere on it to add spin (and drag to move it).
  - It does NOT close on double-click (that fought with clicking to spin);
    `/clear` puts it away (see CommandHandler.stop_session_effects).

Tip: preview edits without launching the whole app with
`python tools/preview_spinner.py`.
"""

import math

from PySide6.QtWidgets import QWidget
from PySide6.QtCore import Qt, QTimer, QPointF
from PySide6.QtGui import QPainter, QColor, QPixmap


# ── Hand-editable pixel art — DRAW THE TOP ARM ONLY (legend in docstring) ────
# The other three arms are generated by rotating the top arm (see _enforce_4fold).
SPINNER_ART = [
    "...........................................",
    "...........................................",
    "...................WWWWW...................",
    "..................WWWRWWW..................",
    ".................WWRRRRRWW.................",
    "................WWRR...RRWW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WWRR...RRWW................",
    ".................WWRRRRRWW.................",
    "..................BWWRWWB..................",
    "..................BWWWWWB..................",
    "..................BBWWWBB..................",
    ".................BBBWWWBBB.................",
    ".....WWWWWW.....BBBBBWBBBBB.....WWWWWW.....",
    "....WWRRRRWW...BBBBRRRRRBBBB...WWRRRRWW....",
    "...WWRRRRRRWBBBBBBRR...RRBBBBBBWRRRRRRWW...",
    "..WWRR....RRWWBBBRR.....RRBBBWWRR....RRWW..",
    "..WWR......RWWWWBR.......RBWWWWR......RWW..",
    "..WRR......RRWWWWR.......RWWWWRR......RRW..",
    "..WWR......RWWWWBR.......RBWWWWR......RWW..",
    "..WWRR....RRWWBBBRR.....RRBBBWWRR....RRWW..",
    "...WWRRRRRRWBBBBBBRR...RRBBBBBBWRRRRRRWW...",
    "....WWRRRRWW...BBBBRRRRRBBBB...WWRRRRWW....",
    ".....WWWWWW.....BBBBBWBBBBB.....WWWWWW.....",
    ".................BBBWWWBBB.................",
    "..................BBWWWBB..................",
    "..................BWWWWWB..................",
    "..................BWWRWWB..................",
    ".................WWRRRRRWW.................",
    "................WWRR...RRWW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WRR.....RRW................",
    "................WWRR...RRWW................",
    ".................WWRRRRRWW.................",
    "..................WWWRWWW..................",
    "...................WWWWW...................",
    "...........................................",
    "...........................................",
]


# 4-fold symmetry now lives in techdeck.ui.pixel_art (shared with .tdart
# spinner variants); see enforce_4fold there.
from techdeck.ui.pixel_art import enforce_4fold as _enforce_4fold

# The symmetric grid actually rendered (top arm rotated into all four).
_ART = _enforce_4fold(SPINNER_ART)
CELL = 7                                 # px per art cell
_ART_H = len(_ART)
_ART_W = max(len(r) for r in _ART)


def _render_spinner_pixmap(colors: dict) -> QPixmap:
    """Render the symmetric art to a pixmap: auto-trace a dark outline around it
    (and the holes), then paint each cell in its themed colour."""
    cmap = {"B": colors["body"], "W": colors["wing"], "R": colors["ring"],
            "H": colors["highlight"], "o": colors["outline"]}
    rows = _ART

    def filled(x, y):
        return 0 <= y < _ART_H and 0 <= x < len(rows[y]) and rows[y][x] != "."

    pm = QPixmap(_ART_W * CELL, _ART_H * CELL)
    pm.fill(Qt.GlobalColor.transparent)
    p = QPainter(pm)
    p.setPen(Qt.PenStyle.NoPen)
    # Outline pass: every empty cell touching a filled cell (silhouette + holes).
    for y in range(_ART_H):
        for x in range(_ART_W):
            if filled(x, y):
                continue
            if any(filled(x + dx, y + dy)
                   for dx in (-1, 0, 1) for dy in (-1, 0, 1) if dx or dy):
                p.fillRect(x * CELL, y * CELL, CELL, CELL, colors["outline"])
    # Body pass: each art cell in its colour.
    for y in range(_ART_H):
        row = rows[y]
        for x in range(len(row)):
            ch = row[x]
            if ch == ".":
                continue
            p.fillRect(x * CELL, y * CELL, CELL, CELL, cmap.get(ch, colors["body"]))
    p.end()
    return pm


def _render_variant_pixmap(variant: str):
    """Render an equipped store spinner from assets/sprites/<variant>.tdart using
    its OWN fixed palette (not the theme), forced 4-fold symmetric. Returns None
    if it can't be loaded so the caller falls back to the default spinner."""
    import sys
    from pathlib import Path
    from techdeck.ui import pixel_art
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        base = Path(sys._MEIPASS) / "assets" / "sprites"
    else:
        base = Path(__file__).resolve().parents[3] / "assets" / "sprites"
    fn = base / f"{variant}.tdart"
    if not fn.exists():
        return None
    try:
        data = pixel_art.enforce_4fold_data(pixel_art.load(fn))
        return pixel_art.render(data, scale=CELL)
    except Exception:
        return None


class FidgetSpinnerWindow(QWidget):
    """Frameless, always-on-top pixel-art four-arm spinner. Click to add spin,
    drag to move. Closed via /clear (no double-click-to-close)."""

    WINDOW_SIZE = max(_ART_H, _ART_W) * CELL

    FRICTION = 0.9985     # per ~60fps frame — low, so a flick keeps it spinning
    CLICK_IMPULSE = 3.0   # radians/sec added per click

    def __init__(self, parent=None, variant=None):
        super().__init__(parent)
        self._angle = 0.0      # radians
        self._velocity = 1.0   # radians/sec
        # An equipped store variant (e.g. "spinner_beyblade") renders from its
        # own .tdart with its own fixed palette; otherwise the default themed
        # spinner is used.
        self._pixmap = _render_variant_pixmap(variant) if variant else None
        if self._pixmap is None:
            self._pixmap = _render_spinner_pixmap(self._theme_colors())

        self.setWindowFlags(
            Qt.WindowType.FramelessWindowHint
            | Qt.WindowType.WindowStaysOnTopHint
            | Qt.WindowType.Tool
        )
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        size = max(self._pixmap.width(), self._pixmap.height())
        self.setFixedSize(size, size)
        self.setCursor(Qt.CursorShape.PointingHandCursor)

        self._timer = QTimer(self)
        self._timer.setInterval(16)  # ~60fps
        self._timer.timeout.connect(self._tick)
        self._timer.start()

        self._drag_pos = None

    @staticmethod
    def _theme_colors() -> dict:
        """The original theme-palette colour set: body (hub/arms) = pressed accent,
        wings = secondary accent_two (the CTA slot — where cyberpunk's red/pink
        lives), bearing rings = text, outline = a darkened accent, and an optional
        highlight = a lighter wing tone."""
        try:
            from techdeck.ui.theme_manager import get_theme_manager
            pal = get_theme_manager().get_current_palette()
            body, wing = QColor(pal.accent_pressed), QColor(pal.accent_two)
            ring, outline = QColor(pal.text), QColor(pal.accent).darker(300)
        except Exception:
            body, wing = QColor(0x1F, 0x67, 0x90), QColor(0xF5, 0xC5, 0x18)
            ring, outline = QColor(0xEC, 0xEC, 0xEC), QColor(0x10, 0x28, 0x38)
        return {
            "body": body,
            "wing": wing,
            "ring": ring,
            "outline": outline,
            "highlight": wing.lighter(150),
        }

    def _tick(self):
        self._velocity *= self.FRICTION
        self._angle += self._velocity * 0.016  # 16ms frame
        self.update()

    def mousePressEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            self._velocity += self.CLICK_IMPULSE
            self._drag_pos = event.globalPosition().toPoint()

    def mouseMoveEvent(self, event):
        if self._drag_pos is not None and event.buttons() & Qt.MouseButton.LeftButton:
            delta = event.globalPosition().toPoint() - self._drag_pos
            self.move(self.pos() + delta)
            self._drag_pos = event.globalPosition().toPoint()

    def mouseReleaseEvent(self, event):
        self._drag_pos = None

    def paintEvent(self, event):
        painter = QPainter(self)
        # Smoothing OFF keeps the pixels hard-edged at every rotation angle.
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, False)
        painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, False)
        painter.translate(self.WINDOW_SIZE / 2.0, self.WINDOW_SIZE / 2.0)
        painter.rotate(math.degrees(self._angle))
        # Float offset so the art centre sits exactly on the rotation pivot (an
        # int offset on an odd-sized pixmap left it a half-pixel off -> wobble).
        painter.drawPixmap(QPointF(-self._pixmap.width() / 2.0,
                                   -self._pixmap.height() / 2.0), self._pixmap)
        painter.end()
