"""Locate and open the bundled TechDeck User Guide PDF.

The guide is generated by tools/build_user_guide.py into assets/docs/ (a
build.ps1 step regenerates it for every shipped build; the whole assets tree
ships via TechDeck.spec datas). Two surfaces open it: the /guide console
command and Settings > Help & Feedback > Open User Guide.
"""

import os
import sys
from pathlib import Path

GUIDE_FILENAME = "TechDeck User Guide.pdf"


def guide_path() -> Path:
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        return Path(sys._MEIPASS) / "assets" / "docs" / GUIDE_FILENAME
    return Path(__file__).resolve().parents[2] / "assets" / "docs" / GUIDE_FILENAME


def open_guide() -> tuple[bool, str]:
    """Open the guide in the default PDF viewer.

    Returns (ok, message): on success the message is the path opened; on
    failure it says what happened, worded for the person reading it.
    """
    path = guide_path()
    if not path.exists():
        if getattr(sys, "frozen", False):
            return False, ("The User Guide didn't ship with this build. "
                           "Please report it with Submit Feedback.")
        return False, ("User Guide PDF not found (dev mode). Build it with: "
                       "python tools/build_user_guide.py")
    try:
        os.startfile(str(path))  # default PDF viewer
    except OSError as exc:
        return False, f"Couldn't open the User Guide: {exc}"
    return True, str(path)
