"""
Plugin icon rendering for the Windows-Settings-style tile grid.

Resolution order for a plugin's tile icon:
  1. An image file shipped in the plugin folder, named by the plugin.json `icon`
     field (e.g. "icon.png" / "icon.svg"). Resolved relative to plugin.path.
  2. An emoji glyph, if `icon` is a short non-filename string (legacy plugins set
     one here). Rendered centered, transparent background.
  3. A family-colored rounded-square monogram ("911" / "922" / name initials).
     This guarantees every tile has a recognizable icon before real art exists.

`plugin_icon_pixmap(plugin, size)` is the single entry point used by the tiles.
"""

import sys
from pathlib import Path

from PySide6.QtCore import Qt, QSize, QRectF
from PySide6.QtGui import (
    QPixmap, QPainter, QColor, QFont, QBrush, QPainterPath, QIcon,
)

# Custom pixel-art tile set (generated by tools/generate_tile_icons_32.py). Each
# plugin maps to a subject "key"; the actual PNG is per-theme:
#   assets/icons/tile icons/TechDeck pixel 32/<theme>/<key>.png
# Keyed on the RUNTIME plugin id. The art is bundled with the build via the
# spec's assets entry.
#
# A key that isn't a themed tile resolves to a generated PACK icon instead
# (full-color art from tools/generate_pack_icons.py, under "TechDeck pack
# pixel" / "Icons8 characters pixel" / "Icons socialmedia pixel"). Those are
# NOT theme-recolored — they render in their native colors on every theme.
# That's how 922_formingfinder uses "futurama_bender" and customer_dxf_quoting
# uses "blueprint".
PLUGIN_ICON_KEYS = {
    "922_setup":            "icons8-toolbox",
    "911_setup":            "microsoft_excel_2019",
    "911_batch_repeater":   "repeat",
    "911_remove_ticket":    "scissors",
    "911_po_pdf_extractor": "claw",
    "911_sketch_extractor": "sym_picture",
    "911_sspo_award_review": "stopwatch",
    "922_pallet_stamper":   "stamp",
    "922_formingfinder":    "futurama_bender",
    "922_kitting":          "toolbox",
    "922_lst_organizer":    "sym_opened_folder",
    "911_lst_organizer":    "sym_opened_folder",
    "922_runtime_genie":    "lamp",
    "922_batch_repeater":   "copy",
    "batch_auditor":        "badge",
    "qr_code_generator":    "qr",
    "customer_dxf_quoting": "blueprint",
    "qa_gemba_analyzer":    "magnifier",
    "911_sspo_invoicing_prep": "scrooge_mcduck",
    "902_dxf_prep":         "ruler",
    "911_baked_beans_wild_ride": "mr_beans",
    "sheet_metal_calculators": "calculator",
}

# Generated pack sets (tools/generate_pack_icons.py) searched when a key is not a
# themed pixel-32 tile. Native colors, not theme-recolored.
_PACK_SETS = ("TechDeck pack pixel", "Icons8 characters pixel", "Icons socialmedia pixel")

# Pack icons that ship directional "eye follow" sprites alongside the base PNG
# (<key>_<up|down|left|right|up_left|...>.png, generated with the base by
# tools/generate_pack_icons.py). The Home tile animates these so the sprite's
# pupils track the cursor; the base icon (looking straight at the camera) is
# what every other surface shows.
EYE_FOLLOW_KEYS = {"mr_beans"}

# Themes that have a generated icon palette on disk. Custom user themes fall back
# to the "dark" set.
_PIXEL_THEMES = {"dark", "light", "cherry_blossom", "blue", "cyberpunk", "matrix"}


def _tile_icons_dir() -> Path:
    """Folder holding the central tile PNGs (frozen-build aware)."""
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        base = Path(sys._MEIPASS) / "assets"
    else:
        base = Path(__file__).resolve().parents[2] / "assets"
    return base / "icons" / "tile icons"


def _current_theme_name() -> str:
    try:
        from techdeck.ui.theme_manager import get_theme_manager
        return get_theme_manager().get_current_theme()
    except Exception:
        return "dark"

# Fixed, theme-independent family colors for the monogram fallback. Chosen to
# read well on both the dark and light app backgrounds.
_FAMILY_COLORS = {
    "902": "#06B6D4",   # cyan
    "911": "#3B82F6",   # blue
    "922": "#F59E0B",   # amber
    "General": "#8B5CF6",  # violet
    "QA": "#10B981",    # emerald
}

# Suffixes we treat as "this `icon` value is a file, not an emoji".
# .tdart is TechDeck's own pixel-art format (rendered via pixel_art).
_IMAGE_EXTS = {".png", ".svg", ".jpg", ".jpeg", ".ico", ".webp", ".bmp", ".tdart"}

# Render at this multiple of the requested logical size, then tag the pixmap
# with the matching device-pixel-ratio so generated icons stay crisp on HiDPI.
_SCALE = 2


def _icon_is_file(icon: str) -> bool:
    return bool(icon) and Path(icon).suffix.lower() in _IMAGE_EXTS


def _pack_icon_path(key: str) -> Path | None:
    """Path to a generated PACK icon (native colors, not themed), or None."""
    base = _tile_icons_dir()
    for pack in _PACK_SETS:
        candidate = base / pack / f"{key}.png"
        if candidate.exists():
            return candidate
    return None


def eye_follow_key(plugin) -> str | None:
    """This plugin's base pack-icon key if it ships eye-follow sprites, else None."""
    key = PLUGIN_ICON_KEYS.get(getattr(plugin, "id", None))
    return key if key in EYE_FOLLOW_KEYS else None


def pack_icon_pixmap(key: str, size: int) -> QPixmap | None:
    """Load a generated pack icon by raw key (native colors), or None if absent.

    Same crisp nearest-neighbour scaling as the tile pipeline; used by the
    eye-follow animation to load the directional sprite variants directly.
    """
    path = _pack_icon_path(key)
    if path is None:
        return None
    pm = QPixmap(str(path))
    if pm.isNull():
        return None
    if pm.width() != size or pm.height() != size:
        pm = pm.scaled(size, size, Qt.AspectRatioMode.KeepAspectRatio,
                       Qt.TransformationMode.FastTransformation)
    return pm


def _load_pixel_icon(plugin, size: int) -> QPixmap | None:
    """Load the theme-matched pixel-art tile icon for this plugin, or None.

    Falls back to a non-themed generated pack icon when the key isn't a themed
    pixel-32 tile (e.g. a brand/character icon like "futurama_bender").
    """
    key = PLUGIN_ICON_KEYS.get(getattr(plugin, "id", None))
    if not key:
        return None
    theme = _current_theme_name()
    folder = theme if theme in _PIXEL_THEMES else "dark"  # custom themes -> dark
    pixel_dir = _tile_icons_dir() / "TechDeck pixel 32"
    path = pixel_dir / folder / f"{key}.png"
    if not path.exists():
        path = pixel_dir / "dark" / f"{key}.png"
    if not path.exists():
        path = _pack_icon_path(key)  # non-themed brand/character pack art
    if path is None or not path.exists():
        return None
    pm = QPixmap(str(path))
    if pm.isNull():
        return None
    if pm.width() != size or pm.height() != size:
        # Nearest-neighbor: these are pixel-art tiles, so smooth/bilinear
        # scaling blurs them (most visible on the 48px library tiles and on
        # detailed art like futurama_bender). Fast keeps pixels hard-edged.
        pm = pm.scaled(size, size, Qt.AspectRatioMode.KeepAspectRatio,
                       Qt.TransformationMode.FastTransformation)
    return pm


def _load_icon_file(plugin, size: int) -> QPixmap | None:
    """Load an icon image shipped alongside the plugin, or None if absent/bad."""
    icon = getattr(plugin, "icon", None)
    if not _icon_is_file(icon):
        return None
    path = Path(getattr(plugin, "path", ".")) / icon
    if not path.exists():
        return None
    # TechDeck pixel-art icons (.tdart) render via pixel_art at integer scale,
    # then scale to the requested size with nearest-neighbour (stay crisp).
    if path.suffix.lower() == ".tdart":
        try:
            from techdeck.ui import pixel_art
            data = pixel_art.load(path)
            w, h = pixel_art.dimensions(data)
            pm = pixel_art.render(data, scale=max(1, size // max(w, h, 1)))
            if pm.isNull():
                return None
            return pm.scaled(size, size, Qt.AspectRatioMode.KeepAspectRatio,
                             Qt.TransformationMode.FastTransformation)
        except Exception:
            return None
    # QIcon handles both raster (.png/.jpg/...) and .svg (via the qsvg image
    # plugin, bundled by the PyInstaller PySide6 hook).
    pm = QIcon(str(path)).pixmap(QSize(size, size))
    if pm.isNull():
        return None
    return pm


def _new_canvas(size: int) -> QPixmap:
    pm = QPixmap(size * _SCALE, size * _SCALE)
    pm.fill(Qt.GlobalColor.transparent)
    pm.setDevicePixelRatio(_SCALE)
    return pm


def _monogram_text(plugin) -> str:
    family = getattr(plugin, "family", "General")
    if family in ("902", "911", "922"):
        return family
    name = (getattr(plugin, "name", "") or "?").strip()
    words = [w for w in name.split() if w]
    if len(words) >= 2:
        return (words[0][0] + words[1][0]).upper()
    return name[:2].upper() if name else "?"


def _monogram(plugin, size: int) -> QPixmap:
    """Family-colored rounded-square tile with the family number or initials."""
    text = _monogram_text(plugin)
    color = QColor(_FAMILY_COLORS.get(getattr(plugin, "family", "General"),
                                      _FAMILY_COLORS["General"]))
    pm = _new_canvas(size)
    p = QPainter(pm)
    p.setRenderHint(QPainter.RenderHint.Antialiasing)
    rect = QRectF(0, 0, size, size)
    path = QPainterPath()
    path.addRoundedRect(rect, size * 0.26, size * 0.26)
    p.fillPath(path, QBrush(color))

    p.setPen(QColor("#FFFFFF"))
    f = QFont('"Segoe UI", Arial, sans-serif')
    f.setBold(True)
    f.setPixelSize(int(size * (0.34 if len(text) >= 3 else 0.44)))
    p.setFont(f)
    p.drawText(rect, Qt.AlignmentFlag.AlignCenter, text)
    p.end()
    return pm


def _emoji(icon: str, size: int) -> QPixmap:
    """Render an emoji glyph centered on a transparent canvas."""
    pm = _new_canvas(size)
    p = QPainter(pm)
    p.setRenderHint(QPainter.RenderHint.Antialiasing)
    f = QFont('"Segoe UI Emoji", "Segoe UI", sans-serif')
    f.setPixelSize(int(size * 0.78))
    p.setFont(f)
    p.drawText(QRectF(0, 0, size, size), Qt.AlignmentFlag.AlignCenter, icon)
    p.end()
    return pm


def plugin_icon_pixmap(plugin, size: int = 48) -> QPixmap:
    """Return a QPixmap for a plugin's tile icon (never None)."""
    pm = _load_pixel_icon(plugin, size)
    if pm is not None:
        return pm
    pm = _load_icon_file(plugin, size)
    if pm is not None:
        return pm
    icon = getattr(plugin, "icon", None)
    if icon and not _icon_is_file(icon):
        return _emoji(icon, size)
    return _monogram(plugin, size)
